# This is a basic workflow to help you get started with Actions

name: Static Analysis

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - develop
      - master

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: PHPStan
      uses: docker://oskarstark/phpstan-ga
      with:
        args: analyse App/
